#!/usr/bin/env python
import socket, sys

UDP_IP = "0.0.0.0"
try:
    UDP_PORT = int(sys.argv[1])
except ValueError:
    print 'Specified port is not a number'
    sys.exit(1)

# haben wir einen gueltigen Port
if not isinstance( UDP_PORT, int ) or not  4464 <= UDP_PORT <= 4500:
    print 'Specified port (', UDP_PORT, ') is invalid.'
    print 'Valid port range: 4464 - 4500'
    sys.exit(1)

# Lass uns die socket erzeugen
try:
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind((UDP_IP, UDP_PORT))
except socket.error, msg:
    sys.stderr.write("[ERROR] %s\n" % msg[1])
    sys.exit(1)

addr = None

while True:
    data, addr = sock.recvfrom(16400)
    sock.sendto(data, addr)
