#!/usr/bin/env python
import socket, sys

UDP_IP = "0.0.0.0"
try:
    UDP_PORT = int(sys.argv[1])
except ValueError:
    print 'Specified port is not a number'
    sys.exit(1)

# haben wir einen gueltigen Port
if not isinstance( UDP_PORT, int ) or not  4464 <= UDP_PORT <= 5200:
    print 'Specified port (', UDP_PORT, ') is invalid.'
    print 'Valid port range: 4464 - 4500'
    sys.exit(1)

# Lass uns die socket erzeugen
try:
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind((UDP_IP, UDP_PORT))
except socket.error, msg:
    sys.stderr.write("[ERROR] %s\n" % msg[1])
    sys.exit(1)

addr = None
client1 = None
client2 = None
stealing = 0

while True:
    data, addr = sock.recvfrom(16400) # buffer size is 1024 bytes

    # Assigning clients
    if addr != client1 and addr != client2:
        if stealing == 0:
            client1 = addr
        else:
            client2 = addr
        stealing = (stealing + 1) % 2

    # transmit data
    if client1 and client2:
        if addr == client1:
            sock.sendto(data, client2)
        elif addr == client2:
            sock.sendto(data, client1)
