#!/bin/bash

# DEFAULTS
SCRIPTNAME=$(basename $0)
NUMOFCHANNELS=2
BITRES=16
SAMPLERATE=48000
BLOCKSIZE=128
NUMOFINSTANCES=1
CLIENTOF="telematic.zhdk.ch"
DURATION=10

VALIDBITRESLIST="8 16 24 32"
VALIDSAMPLERATELIST="22050 32000 44100 48000 88200 96000 192000"
VALIDBLOCKSIZELIST="64 128 256 512 1024 2048 4096"

# Parse cmdline arguments
help=false
while [ $# -gt 0 ]
do
  case "$1" in
    -n|--numofchannels)    NUMOFCHANNELS="$2"; shift;;
    -b|--bitres)           BITRES="$2"; shift;;
    -r|--samplerate)       SAMPLERATE="$2"; shift;;
    -s|--blocksize)        BLOCKSIZE="$2"; shift;;
    -i|--instances)        NUMOFINSTANCES="$2"; shift;;
    -c|--client)           CLIENTOF="$2"; shift;;
    -d|--duration)         DURATION="$2"; shift;;
    -h|--help)             help=true;;
    -*) printerr "$SCRIPTNAME: error - unrecognized option '$1'"
        printerr "use '$SCRIPTNAME --help' to get a list of available options"
        exit 1;;
    *)  break;;
  esac
  shift
done

# show help
if $help
then
  cat << EOF

$SCRIPTNAME
------------

Tool for testing network connection for Telematic Performances. It's
basically a wrapper around iperf3.

The tool emulates the payload of one or many jacktrip connections
and reports jitter and lost packages.

For a given number of channels and bitres, you may want to tweak
the buffersize and test what works best for the current network
connection.

CMDLINE OPTIONS:

    -n|--numofchannels INT    number of channels
    -b|--bitres INT           bit resolution (8, 16, 24, 32)
    -r|--samplerate INT       samplerate
    -s|--blocksize INT        blocksize
    -i|--instances INT        run INT number of clients simultaneously
    -c|--client HOST          set the host to connect to
    -d|--duration INT         duration of a test in seconds
    -h|--help                 show this help

EOF
  exit

fi

# check BITRES
if [[ ! $VALIDBITRESLIST =~ (^|[[:space:]])$BITRES($|[[:space:]]) ]]
then
  echo "Given bitres ('$BITRES') is not valid."
  echo "Valid bitres values are: $VALIDBITRESLIST"
  exit 1
fi

# check SAMPLERATE
if [[ ! $VALIDSAMPLERATELIST =~ (^|[[:space:]])$SAMPLERATE($|[[:space:]]) ]]
then
  echo "Given samplerate ('$SAMPLERATE') is not valid."
  echo "Valid samplerate values are: $VALIDSAMPLERATELIST"
  exit 1
fi

# check BLOCKSIZE
if [[ ! $VALIDBLOCKSIZELIST =~ (^|[[:space:]])$BLOCKSIZE($|[[:space:]]) ]]
then
  echo "Given samplerate ('$BLOCKSIZE') is not valid."
  echo "Valid samplerate values are: $VALIDBLOCKSIZELIST"
  exit 1
fi

# check NUMOFCHANNELS
if  (( NUMOFCHANNELS < 2 )) || (( NUMOFCHANNELS > 64 ))
then
  echo "Given number of channels ('$NUMOFCHANNELS') is not valid."
  echo "Valid range is: 2-64"
  exit 1
fi

# Calculate UDP packetsize (in bytes)
# The jacktrip header size is 16 bytes
PACKETSIZE=$(( BLOCKSIZE * NUMOFCHANNELS * BITRES / 8 + 16 ))

# Calculate packet rate
PACKETRATE=$(bc <<< "scale=2; $SAMPLERATE/$BLOCKSIZE")

# Calculate bandwidth
BANDWIDTH=$(bc <<< "scale=3; $PACKETRATE*$PACKETSIZE*8/1000000")

echo -e "Configured options:\033[32m"
echo "  BITRES:       $BITRES    (-b)"
echo "  SAMPLERATE:   $SAMPLERATE (-r)"
echo "  BLOCKSIZE:    $BLOCKSIZE   (-s)"
echo "  CHANNELS:     $NUMOFCHANNELS     (-n)"
echo "  DURATION:     ${DURATION}s   (-d)"
echo -e "\033[0m"
echo -e "Calculated parameters:\033[35m"
echo "  PACKETSIZE:   ${PACKETSIZE} bytes"
echo "  PACKETRATE:   ${PACKETRATE}/s"
echo "  BANDWIDTH:    ${BANDWIDTH}Mb/s"
echo -e "\033[0m"
echo "-------------------------------------------------------------------"
echo "Now running test:"
echo -e "\033[34mLOCAL >>>>>>>>>>>>>>> TELEMATIC server\033[0m"
echo "Exuting command:"
echo -e "\033[31miperf3 -u -c ${CLIENTOF} -p 6000 -l ${PACKETSIZE} -b ${BANDWIDTH}M -i 2 -t ${DURATION} -P ${NUMOFINSTANCES} \033[0m"
iperf3 -u -c ${CLIENTOF}    -p 6000 -l ${PACKETSIZE} -b ${BANDWIDTH}M -i 2 -t ${DURATION} -P ${NUMOFINSTANCES}
echo -e "\033[34mLOCAL <<<<<<<<<<<<<<< TELEMATIC server\033[0m"
echo "Executing command:"
echo -e "\033[31miperf3 -u -c ${CLIENTOF} -R -p 6000 -l ${PACKETSIZE} -b ${BANDWIDTH}M -i 2 -t ${DURATION} -P ${NUMOFINSTANCES} \033[0m"
iperf3 -u -c ${CLIENTOF} -R -p 6000 -l ${PACKETSIZE} -b ${BANDWIDTH}M -i 2 -t ${DURATION} -P ${NUMOFINSTANCES}
